CREATE TABLE LOG
(user_id VARCHAR(50) NOT NULL, 
time DATE, 
bet VARCHAR(50) NOT NULL,
win VARCHAR(50) NOT NULL);

CREATE TABLE USERS
(user_id VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
geo VARCHAR(50) NOT NULL);
